name: Test Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  get-action-js:
    name: Test Get Employee Action (JavaScript)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: get-action-js/.nvmrc
          cache-dependency-path: get-action-js
          cache: npm

      - name: Install Dependencies
        run: npm ci
        working-directory: get-action-js

      - name: Test Get Employee (JavaScript) Action
        id: get-action-js
        uses: ./get-action-js
        with:
          github-username: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}

      - name: Print Slack User ID
        run: echo "${{ steps.get-action-js.outputs.slack-user-id }}"
